title: Ramblings of a developer
author:
  name: M Z Worthington
  email: matt@siliconpanda.com
description: >- 
  Hi folks 👋👋
  My name is Matthew, I'm a dev. Thanks for popping by.
baseurl: ""
url: "https://mzworthington.co.uk"
social_links:
  twitter: worthington10
  github:  worthington10tw
  instagram: worthington10
plugins:
 - jekyll-feed
 - jekyll-seo-tag
skin: dark
sass:
    sass_dir: _sass
    style: compact 