title: Ramblings of a developer
author:
  name: M Z Worthington
  email: matt@siliconpanda.com
  twitter: worthington10
  picture: /assets/me.webp
description: >- 
  Hi folks 👋👋
  I'm Matthew, a security specialist and tech principal @ <a href="https://www.thoughtworks.com/" target="_blank">Thoughtworks</a>.

  Thanks for popping by.
baseurl: ""
url: "https://mzworthington.co.uk"
social_links:
  twitter: worthington10
  github:  worthington10tw
  instagram: worthington10
  linkedin: worthington10
excerpt_separator: <!--more-->
locale: en_GB
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-spaceship
sass:
    sass_dir: _sass
    style: compact 
permalink: /:categories/:title
collections:
  category:
    output: true
defaults:
  -
    scope:
      path: "about"
    values:
      layout: "about"
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - scripts/
  - .gitignore/
  - .ruby-version/
  - Brewfile/