title: Ramblings of a developer
author:
  name: M Z Worthington
  email: matt@siliconpanda.com
description: >- 
  Hi folks 👋👋
  My name is Matthew and I work in tech. 
  Thanks for popping by.
baseurl: ""
url: "https://mzworthington.co.uk"
social_links:
  twitter: worthington10
  github:  worthington10tw
  instagram: worthington10
  linkedin: worthington10
excerpt_separator: <!--more-->
plugins:
 - jekyll-feed
 - jekyll-seo-tag
sass:
    sass_dir: _sass
    style: compact 
permalink: pretty
image: /assets/me.jpg